{{- if .Values.cloudflared.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hbweb.fullname" . }}-cloudflared-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "hbweb.labels" . | nindent 4 }}
type: Opaque
data:
  tunnel-token: {{ .Values.secrets.cloudflareTunnelToken | b64enc | quote }}
{{- end }}
