apiVersion: v1
kind: Service
metadata:
  name: {{ include "hbweb.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "hbweb.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    {{- include "hbweb.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
